/*
 * Auto-Generated by NUKE!
 *   http://arbotix.googlecode.com
 */

#include <ax12.h>
#include <BioloidController.h>
#include <Commander.h>
#include "nuke.h"

Commander command = Commander();

void setup(){
  // foot sensors
  pinMode(2,OUTPUT);
  pinMode(3,OUTPUT);
  pinMode(4,OUTPUT);
  pinMode(5,OUTPUT);
  digitalWrite(31, HIGH);
  digitalWrite(30, HIGH);
  digitalWrite(29, HIGH);
  digitalWrite(28, HIGH);
  
  pinMode(0,OUTPUT);
  // setup IK
  setupIK();
  gaitSelect(RIPPLE);
  // setup serial
  Serial.begin(38400);

  // wait, then check the voltage (LiPO safety)
  delay (1000);
  float voltage = (ax12GetRegister (1, AX_PRESENT_VOLTAGE, 1)) / 10.0;
  Serial.print ("System Voltage: ");
  Serial.print (voltage);
  Serial.println (" volts.");
  if (voltage < 10.0)
     while(1);

  // stand up slowly
  bioloid.poseSize = 16; // 12 + tail 
  bioloid.readPose();
  doIK();
  bioloid.interpolateSetup(1000);
  while(bioloid.interpolating > 0){
    bioloid.interpolateStep();
    delay(3);
  }
  ax12SetRegister2(15,AX_CW_COMPLIANCE_SLOPE,1);
  ax12SetRegister2(16,AX_CW_COMPLIANCE_SLOPE,1);
  //gaitSelect(AMBLE);
  //Xspeed = 100;
}

int k = 0;

void loop(){
  // update IK if needed
  if(bioloid.interpolating == 0){
    //delay(2500);
    doIK();
    bioloid.interpolateSetup(tranTime);
    k++;
    //delay(2000);
    //if(k > 60)
    //  Xspeed = 0;
  }
  // update joints (or go relaxed)
  //if((mode > 0) && ((PINA&0x0f) == 0x0f)){  // operational, but all feet in air, relax
  //  mode = 0;
  //  int i;
  //  for(i= 0; i<16; i++)
  //    Relax(i+1);
  //  digitalWrite(0,LOW);
  //}else if(mode > 0){
  bioloid.interpolateStep();
  //}else if((PINA&0x0f) == 0){
  //  // back on ground
  //  mode = 1;
  //  digitalWrite(0,HIGH);
  //}
  // take commands
  if(command.ReadMsgs() > 0){
    digitalWrite(0,HIGH-digitalRead(0));
    Xspeed = 1 * ((command.walkV));
    if((command.buttons&BUT_LT) > 0)
      Yspeed = (command.walkH);
    else
      Rspeed = -(command.walkH)/75.0;
    bodyRotY = (((float)command.lookV))/250.0;
    //bodyPosX = command.lookV/5;
    if((command.buttons&BUT_RT) > 0)
      bodyRotX = ((float)command.lookH)/250.0;
    else
      //spinePosY = command.lookH/2;
      bodyRotZ = ((float)command.lookH)/250.0;
  }
  //digitalWrite(2,HIGH-digitalRead(31));
  //digitalWrite(3,HIGH-digitalRead(30));
  //digitalWrite(4,HIGH-digitalRead(29));
  //digitalWrite(5,HIGH-digitalRead(28));
}

