---
# Install couchdb (v3)
- name: Install couchdb prereqs
  become: yes
  apt:
    pkg:
      - apt-transport-https
      - gnupg
      - ca-certificates
- name: Configure apt key for couchdb
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 8756C4F765C9AC3CB6B85D62379CE192D401AB61
- name: Configure apt source for couchdb
  become: yes
  apt_repository:
    repo: 'deb https://apache.bintray.com/couchdb-deb {{ ansible_lsb.codename }} main'
    filename: 'couchdb'
    update_cache: yes
- name: Install couchdb
  become: yes
  apt:
    pkg: couchdb
# TODO: set bind: 0.0.0.0
# TODO: set admin: Password
# TODO: restart service (it will die when there is no password)
