/*
 * Auto-Generated by NUKE!
 *   http://arbotix.googlecode.com
 */

#include <ax12.h>
#include <BioloidController.h>
#include <Commander.h>
#include "nuke.h"
#include <Motors2.h>

Motors2 motors = Motors2();
Commander command = Commander();

int tilt;

void setup(){
    pinMode(0,OUTPUT);
    // setup IK
    setupIK();
    gaitSelect(RIPPLE);
    // setup serial
    Serial.begin(38400);

    // wait, then check the voltage (LiPO safety)
    delay (1000);
    float voltage = (ax12GetRegister (1, AX_PRESENT_VOLTAGE, 1)) / 10.0;
    //Serial.print ("System Voltage: ");
    //Serial.print (voltage);
    //Serial.println (" volts.");
    //if (voltage < 10.0)
    //    while(1);

    tilt = 512;
    // stand up slowly
    SetPosition(3,tilt);
    bioloid.poseSize = 12;
    bioloid.readPose();
    doIK();
    bioloid.interpolateSetup(1000);
    while(bioloid.interpolating > 0){
        bioloid.interpolateStep();
        delay(3);
    }
}

/* this is the main loop, it repeats over and over again */
void loop(){
  // take commands from a commander or computer
  if(command.ReadMsgs() > 0){
    if(command.buttons&BUT_R3){ gaitSelect(RIPPLE);}
    if(command.buttons&BUT_L4){ gaitSelect(AMBLE);}
    digitalWrite(0,HIGH-digitalRead(0));
    // Guns
    if(command.buttons&BUT_LT){
      motors.set(-240,-240); 
    }else{
      motors.set(0,0);
    }
    //Xspeed = (2*(command.walkV));
    if((command.buttons&BUT_LT) > 0)
      Yspeed = (command.walkH);
    else
      Rspeed = -(command.walkH)/100.0;
    if(Rspeed > 0.5){
      //gaitSelect(AMBLE);
      Xspeed = command.walkH;
    }else if(currentGait == AMBLE){
      Xspeed = 4*command.walkV;
    }else{
      //gaitSelect(RIPPLE);
      Xspeed = 2*command.walkV;
    }
    
    /*bodyRotY = (((float)command.lookV))/250.0;
    if((command.buttons&BUT_RT) > 0)
      bodyRotX = ((float)command.lookH)/250.0;
    else
      bodyRotZ = ((float)command.lookH)/250.0;*/
      
    if(command.lookV > 90){
      tilt -= 8;
    }else if(command.lookV > 10){
      tilt -= 2;
    }else if(command.lookV < -90){
      tilt += 8;
    }else if(command.lookV < -50){
      tilt += 2;
    }
    if(tilt > 570){
      tilt = 570;
    }else if(tilt < 375){
      tilt = 375;
    }
    // R1 resets to home position
    if(command.buttons&BUT_R1){
      tilt = 512; 
    }
    SetPosition(13,tilt);    
      
  }

  // if our previous interpolation is complete, recompute the IK
  if(bioloid.interpolating == 0){
    doIK();
    bioloid.interpolateSetup(tranTime);
  }

  // update joints
  bioloid.interpolateStep();

}

