/*
 * Auto-Generated by NUKE!
 *   http://arbotix.googlecode.com
 */

#include <ax12.h>
#include <BioloidController.h>
#include <Commander.h>
#include <SharpIR.h>
#include "nuke.h"

Commander command = Commander();

void setup(){   
    pinMode(0,OUTPUT);
    int i;
    // setup IK    
    setupIK();    
    gaitSelect(RIPPLE);
    // setup serial
    Serial.begin(38400);
    Serial.println("Begin...");

    for(i=0;i<AX12_MAX_SERVOS;i++)
      dynamixel_bus_config[i] = 1;

    // stand up slowly
    delay(100);
    bioloid.poseSize = 12;
    bioloid.readPose();
    doIK();
    bioloid.interpolateSetup(1000);
    while(bioloid.interpolating > 0){
        bioloid.interpolateStep();
        delay(3);
    }
}

void loop(){
  // update IK if needed
  if(bioloid.interpolating == 0){
    doIK();
    bioloid.interpolateSetup(tranTime);
  }
  // update joints
  bioloid.interpolateStep();
  // take commands 
  if(command.ReadMsgs() > 0){
    digitalWrite(0,HIGH-digitalRead(0));
    // Gaits
    if((command.buttons&BUT_R3)) // && (currentGait!=AMBLE))
      gaitSelect(AMBLE);  
    if((command.buttons&BUT_L4)) // && (currentGait!=RIPPLE))
      gaitSelect(RIPPLE);  
  
    //bodyPosX = (command.walkV);
    travelX = (2*(command.walkV));
    if((command.buttons&BUT_LT) > 0)
      travelY = (command.walkH);
    else
      //bodyPosY = command.walkH;
      travelRotZ = -(command.walkH)/250.0;  
    bodyRotY = (((float)command.lookV))/250.0;
    if((command.buttons&BUT_RT) > 0)
       bodyRotX = ((float)command.lookH)/250.0; 
    else
      SetPosition(15,512-(2*command.lookH)); //bodyRotZ = ((float)command.lookH)/250.0;
  }   
}





/*
//unsigned long Htime;
void loop(){
  // update IK if needed
  if(bioloid.interpolating == 0){
    doIK();
    bioloid.interpolateSetup(65); //tranTime);  // was doing 50
  }
  // update joints
  bioloid.interpolateStep();
  // take commands 
  if(command.ReadMsgs() > 0){
    travelX = ((command.walkV));
    if((command.buttons&WALK_TOP) > 0)
      travelY = (command.walkH);
    else
      travelRotZ = -(command.walkH)/250.0;  
    bodyRotY = (((float)command.lookV))/375.0;
    if((command.buttons&LOOK_TOP) > 0)
      //bodyRotX = ((float)command.lookH)/375.0; 
      bodyPosY = command.lookH/3;
    else
      bodyRotZ = ((float)command.lookH)/375.0;
    /*if(millis() > Htime + 1000){
      if((command.buttons&WALK_3) > 0){
        LIFT_HEIGHT++;
        Htime = millis();
      }
      if((command.buttons&LOOK_4) > 0){
        LIFT_HEIGHT--;  
        Htime = millis();
      }
    }
  }   
}*/

